LogViewWebApplication/Models/DummyContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace LogViewWebApplication.Models
{
    public class DummyContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public DummyContext() : base("name=DummyContext")
        {
        }

        //public System.Data.Entity.DbSet<LogViewWebApplication.Models.LogReadViewModel> LogReadModels { get; set; }
    }
}

LogViewWebApplication/Models/LogReadViewModels.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace LogViewWebApplication.Models
{
    public class LogReadViewModel
    {
        [Required]
        [Display(Name = "Date From")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime TimeFrom { get; set; }

        [Required]
        [Display(Name = "Date To")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime TimeTo { get; set; }

        public int Id { get; set; }
        public int Level { get; set; }
        public int EventId { get; set; }

        [Display(Name = "Task Category")]
        public int TaskCategory { get; set; }
        public int Opcode { get; set; }
        public long RecordId { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime TimeCreated { get; set; }
        public DateTime InsertDate { get; set; }

        public string LogName { get; set; }
        public string ProviderName { get; set; }
        public string LevelDisplayName { get; set; }
        public string UserId { get; set; }
        public string MachineName { get; set; }
        public string Description { get; set; }
        public string OpcodeDisplayName { get; set; }
        public string Keywords { get; set; }
    }
}

LogViewWebApplication/Controllers/LogReadController.cs
using System.Web.Mvc;
using Repository.PostgreSQL;
using System.Configuration;
using AutoMapper;
using System.Collections.Generic;
using LogViewWebApplication.Models;
using SharedModels;
using PagedList;
using System;
using System.Linq;
using Common;

namespace LogViewWebApplication.Controllers
{
    public class LogReadController : Controller
    {
        private string connection = ConfigurationManager.ConnectionStrings["NpgsqlConnection"].ConnectionString;

        public ActionResult Index()
        {
            var vwModel = new LogReadViewModel();
            SetViewData();
            SetDefaults(vwModel);
            return View(vwModel);
        }

        #region helpers
        public ActionResult Post(LogReadViewModel vwModel, int? page)
        {
            QueryDatabase(page, vwModel);
            SetViewData();
            return View("Index", vwModel);
        }
        private void QueryDatabase(int? page, LogReadViewModel vwModel)
        {
            if (vwModel.Description == null && vwModel.TimeFrom == DateTime.MinValue && vwModel.TimeTo == DateTime.MinValue)
                return;

            ViewBag.OnePageOfLogs = new List<LogReadViewModel>().ToPagedList(1, 1);
            var dbModel = new List<EventLogModel>();

            if (Session["dbModel"] == null)
            {
                dbModel = new EventLogRepository(connection).SelectListBetween(vwModel.TimeFrom, vwModel.TimeTo);
                Session["dbModel"] = dbModel;
            }
            else
            {
                dbModel = (List<EventLogModel>)Session["dbModel"];
                vwModel.TimeFrom = new DateTime(vwModel.TimeFrom.Year, vwModel.TimeFrom.Month, vwModel.TimeFrom.Day);
            }


            //Filter TaskCategory
            if (vwModel.TaskCategory > 0)
                dbModel = dbModel.Where(x => x.TaskCategory == vwModel.TaskCategory).ToList();

            //Filter Description
            if (vwModel.Description != null)
                dbModel = dbModel.Where(x => x.Description.Contains(vwModel.Description)).ToList();

            Mapper.Initialize(cfg => cfg.CreateMap<EventLogModel, LogReadViewModel>());
            var vwModel2 = Mapper.Map<List<LogReadViewModel>>(dbModel);

            var pageNumber = page ?? 1;
            var onePageOfLogs = vwModel2.ToPagedList(pageNumber, 25);
            ViewBag.OnePageOfLogs = onePageOfLogs;
        }
        private void SetDefaults(LogReadViewModel vwModel)
        {
            vwModel.TimeFrom = DateTime.Now;
            vwModel.TimeTo = DateTime.Now;
            ViewBag.OnePageOfLogs = new List<LogReadViewModel>().ToPagedList(1, 1);
        }
        private void SetViewData()
        {
            var list = new List<SelectListItem>();
            foreach (var item in Enum.GetValues(typeof(CategoryModel.Categorys)))
            {
                var id = (int)item;
                var desc = item.ToString();

                list.Add(new SelectListItem() {
                    Value = id.ToString(),
                    Text = string.Format("{0} - {1}", id, desc) });
            }
            ViewData["SelectList_TaskCategory"] = list;
        }
        #endregion
    }
}

LogViewWebApplication/Views/LogRead/Index.cshtml
@model LogViewWebApplication.Models.LogReadViewModel
@using PagedList.Mvc;
@using PagedList;

@{
    ViewBag.Title = "Index";
}

<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />
<h2>Event Logs</h2>

@{ 
    var timeFrom = Model.TimeFrom.ToString("dd/MM/yyyy");
    var timeTo = Model.TimeTo.ToString("dd/MM/yyyy");
}
@Html.PagedListPager((IPagedList)ViewBag.OnePageOfLogs, page => Url.Action("Post", new { page, timeFrom, timeTo, Model.TaskCategory, Model.Description }))

@using (Html.BeginForm("Post", "LogRead"))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.TimeFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.TimeFrom, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.TimeTo, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.TaskCategory,
                                (List<SelectListItem>)ViewData["SelectList_TaskCategory"],
                                "ALL",
                                new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="col-md-2">
                <input type="submit" value="Go" class="btn" />
            </div>
        </div>
    </div>
}
<table class="table">
    <tr>
        <th>Event Log Id</th>
        <th>Description</th>
        <th>Task Category</th>
        <th>Logged On</th>
        <th>SQL Inserted On</th>
        <th>Level</th>
        <th>Machine Name</th>
    </tr>

    @foreach (var x in ViewBag.OnePageOfLogs)
    {
        <tr>
            <td>@x.RecordId</td>
            <td>@x.Description</td>
            <td>@x.TaskCategory</td>
            <td>@x.TimeCreated</td>
            <td>@x.InsertDate</td>
            <td>@x.LevelDisplayName</td>
            <td>@x.MachineName</td>
        </tr>
    }
</table>

@Html.PagedListPager((IPagedList)ViewBag.OnePageOfLogs, page => Url.Action("Index", new { page }))

<style type="text/css">
    .container {
        margin-right: 0 !important;
        margin-left: 0 !important;
    }
</style>

LogViewWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Log Reader</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Log Reader", "Index", "LogRead", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Logs", "Index", "LogRead")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Log Reader</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link href="~/Content/bootstrap-datepicker.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>
</body>
</html>

<script type="text/javascript">
    $(document).ready(function () {
        $('input[type=datetime]').datepicker({
            format: "dd/mm/yyyy"
        });
    });
</script>